import React from 'react';
import Head from 'next/head';
import Nav from './Nav';
import Footer from './Footer';

const Layout = ({ children }) => {    
    return(
        <>
            <Head>
                <title>NextJS Craft</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Nav />
            {children}
            <Footer />
        </>

    )
} 

export default Layout; 